alfadoc_admin_area_homepage:
    pattern:  /
    defaults: { _controller: AlfadocAdminAreaBundle:Home:index }

alfadoc_admin_area_login:
    pattern:   /login
    defaults:  { _controller: AlfadocAdminAreaBundle:Security:login }

alfadoc_admin_area_login_check:
    pattern:   /login_check

alfadoc_admin_area_logout:
    pattern:   /logout
